# Generated by Django 4.0.4 on 2022-04-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krautuve', '0002_alter_order_customer_id_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='krautuve.productorder', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='krautuve.product', verbose_name='User'),
        ),
    ]
