# Generated by Django 4.0.4 on 2022-04-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krautuve', '0003_order_status_id_product_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='krautuve.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='krautuve.status', verbose_name='Status'),
        ),
    ]
